#' Smart Extraction of Genomic Regions from Intergenomic Transfers
#' 
#' This function automatically identifies and extracts DNA sequences from a provided 
#' FASTA file based on BLAST results. It intelligently detects whether the sequences 
#' in the FASTA file correspond to the `query_id` or `subject_id` columns in the 
#' input table and maps coordinates accordingly.
#' 
#' @param transfer_function_out A data.frame/tibble generated by 
#'   \code{transfer_function_nuclear}. Must contain columns: \code{query_id}, 
#'   \code{subject_id}, \code{q_start}, \code{q_end}, \code{s_start}, and \code{s_end}.
#' @param fasta_path Character string; the file path to the FASTA file containing 
#'   the sequences to be extracted (e.g., nuclear, mitochondrial, or plastid genome).
#' 

extract_regions <- function(
    transfer_function_out, 
    fasta_path
) {

  sequences <- Biostrings::readDNAStringSet(fasta_path)
  names(sequences) <- sapply(strsplit(names(sequences), "\\s+"), `[`, 1)
  fasta_names <- names(sequences)
  
  q_ids_clean <- sapply(strsplit(as.character(transfer_function_out$query_id), "\\|"), `[`, 1)
  s_ids_clean <- sapply(strsplit(as.character(transfer_function_out$subject_id), "\\|"), `[`, 1)
  
  is_in_query   <- q_ids_clean %in% fasta_names
  is_in_subject <- s_ids_clean %in% fasta_names
  
  valid_idx <- is_in_query | is_in_subject
  if(sum(valid_idx) == 0) stop("No matching IDs from the table were found in the provided FASTA file.")
  
  df_sub <- transfer_function_out[valid_idx, ]
  
  final_ids <- c()
  starts    <- nuc_starts <- numeric()
  ends      <- nuc_ends   <- numeric()
  
  q_sub_clean <- sapply(strsplit(as.character(df_sub$query_id), "\\|"), `[`, 1)
  s_sub_clean <- sapply(strsplit(as.character(df_sub$subject_id), "\\|"), `[`, 1)
  
  for(i in 1:nrow(df_sub)) {
    if(s_sub_clean[i] %in% fasta_names) {
      final_ids[i] <- s_sub_clean[i]
      starts[i]    <- as.numeric(df_sub$s_start[i])
      ends[i]      <- as.numeric(df_sub$s_end[i])
    } else {
      final_ids[i] <- q_sub_clean[i]
      starts[i]    <- as.numeric(df_sub$q_start[i])
      ends[i]      <- as.numeric(df_sub$q_end[i])
    }
  }
  
  ranges_list <- IRanges::IRangesList(
    lapply(1:length(final_ids), function(i) {
      IRanges::IRanges(
        start = min(starts[i], ends[i]), 
        end = max(starts[i], ends[i])
      )
    })
  )
  
  fragments <- Biostrings::extractAt(
    sequences[final_ids], 
    ranges_list
  )
  
  result <- Biostrings::DNAStringSetList(lapply(seq_along(fragments), function(i) {
    if(starts[i] > ends[i]) {
      Biostrings::reverseComplement(fragments[[i]])
    } else {
      fragments[[i]]
    }
  }))
  
  names(result) <- paste0(
    final_ids, "|",
    pmin(starts, ends), "-",
    pmax(starts, ends)
  )
  
  return(result)
}