#' Smart Extraction of Genomic Regions from Intergenomic Transfers
#' 
#' This function automatically identifies and extracts DNA sequences from a provided 
#' FASTA file based on BLAST results. It intelligently detects whether the sequences 
#' in the FASTA file correspond to the `mt_id` or `pt_id` columns in the 
#' input table and maps coordinates accordingly.
#' 
#' @param transfer_function_out A data.frame generated by 
#'   \code{transfer_function}. Must contain columns: \code{mt_id}, 
#'   \code{pt_id}, \code{mt_start}, \code{mt_end}, \code{pt_start}, and \code{pt_end}.
#' @param fasta_path Character string; the file path to the FASTA file containing 
#'   the sequences to be extracted (e.g., mitochondrial or plastid genome).
#' 

extract_regions <- function(
    transfer_function_out, 
    fasta_path
) {

  sequences <- Biostrings::readDNAStringSet(fasta_path)
  names(sequences) <- sapply(strsplit(names(sequences), "\\s+"), `[`, 1)
  fasta_names <- names(sequences)
  
  mt_ids_clean <- sapply(strsplit(as.character(transfer_function_out$mt_id), "\\|"), `[`, 1)
  pt_ids_clean <- sapply(strsplit(as.character(transfer_function_out$pt_id), "\\|"), `[`, 1)
  
  is_in_mt <- mt_ids_clean %in% fasta_names
  is_in_pt <- pt_ids_clean %in% fasta_names
  
  valid_idx <- is_in_mt | is_in_pt
  if(sum(valid_idx) == 0) {
    stop("No matching IDs from the table (mt_id or pt_id) were found in the provided FASTA file.")
  }
  
  df_sub <- transfer_function_out[valid_idx, ]
  mt_sub_clean <- mt_ids_clean[valid_idx]
  pt_sub_clean <- pt_ids_clean[valid_idx]
  
  final_ids <- c()
  starts    <- numeric()
  ends      <- numeric()
  
  for(i in 1:nrow(df_sub)) {
    if(pt_sub_clean[i] %in% fasta_names) {
      final_ids[i] <- pt_sub_clean[i]
      starts[i]    <- as.numeric(df_sub$pt_start[i])
      ends[i]      <- as.numeric(df_sub$pt_end[i])
    } else {
      final_ids[i] <- mt_sub_clean[i]
      starts[i]    <- as.numeric(df_sub$mt_start[i])
      ends[i]      <- as.numeric(df_sub$mt_end[i])
    }
  }
  
  ranges_list <- IRanges::IRangesList(
    lapply(1:length(final_ids), function(i) {
      IRanges::IRanges(
        start = min(starts[i], ends[i]), 
        end = max(starts[i], ends[i])
      )
    })
  )
  
  fragments <- Biostrings::extractAt(
    sequences[final_ids], 
    ranges_list
  )
  
  result <- Biostrings::DNAStringSet(unlist(lapply(seq_along(fragments), function(i) {
    dna <- fragments[[i]][[1]]
    if(starts[i] > ends[i]) {
      Biostrings::reverseComplement(dna)
    } else {
      dna
    }
  })))
  
  names(result) <- paste0(
    final_ids, "|",
    pmin(starts, ends), "-",
    pmax(starts, ends)
  )
  
  return(result)
}